spring:
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    suffix: .html
    template-loader-path: classpath:/templates
    request-context-attribute: request
  datasource:
    url: jdbc:mysql://127.0.0.1/wx?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=CST&autoReconnect=true
    username: root
    password: zjdl
    driverClassName: com.mysql.jdbc.Driver
#mybatis:
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.ty.xcx.demo.mapper
  configuration:
    map-underscore-to-camel-case: true
    interceptors:
server:
  port: 8080
  session:
    cookie:
      max-age:1800000
      timeout:1800000



